import { BADGE_TONES } from '@/components/Badge';

import { AMC_STATUSES } from '../constants';

export const AMC_STATUS_TONES = {
  [AMC_STATUSES.ACTIVE]: BADGE_TONES.SUCCESS,
  [AMC_STATUSES.EXPIRING_SOON]: BADGE_TONES.WARNING,
  [AMC_STATUSES.EXPIRED]: BADGE_TONES.DANGER,
  [AMC_STATUSES.RENEWED]: BADGE_TONES.INFO,
  [AMC_STATUSES.PENDING_FIRST_PAYMENT]: BADGE_TONES.WARNING,
};
