import { BADGE_TONES, Badge } from '@/components/Badge';

import {
  LEAD_PRIORITIES,
  LEAD_PRIORITY_LABELS,
  LEAD_STATUSES,
  LEAD_STATUS_LABELS,
} from '../constants';

const PRIORITY_TONES = {
  [LEAD_PRIORITIES.HIGH]: BADGE_TONES.WARNING,
  [LEAD_PRIORITIES.MEDIUM]: BADGE_TONES.INFO,
  [LEAD_PRIORITIES.LOW]: BADGE_TONES.NEUTRAL,
};

const STATUS_TONES = {
  [LEAD_STATUSES.NEW]: BADGE_TONES.INFO,
  [LEAD_STATUSES.CONTACTED]: BADGE_TONES.NEUTRAL,
  [LEAD_STATUSES.QUALIFIED]: BADGE_TONES.ACCENT,
  [LEAD_STATUSES.WON]: BADGE_TONES.SUCCESS,
  [LEAD_STATUSES.LOST]: BADGE_TONES.DANGER,
};

export function PriorityBadge({ priority }) {
  return <Badge tone={PRIORITY_TONES[priority]}>{LEAD_PRIORITY_LABELS[priority]}</Badge>;
}

export function StatusBadge({ status }) {
  return <Badge tone={STATUS_TONES[status]}>{LEAD_STATUS_LABELS[status]}</Badge>;
}
